### ISSUE TITLE
导入Cookie的格式？

### ISSUE THREAD

**Issue by dingyx99** [spencerwooo/PaimonMenuBar#1]
我直接复制粘贴的 Netscape HTTP Cookie File 格式的 txt 文件，提示我不对，请问一下导入的 Cookie 是需要什么格式的？

**Comment by spencerwooo** [comment]
咦，试一下在 <https://bbs.mihoyo.com/ys> 登录后打开 devtools 然后：

```
document.cookie
```

再复制？

![CleanShot 2022-03-30 at 13 30 19@2x](https://user-images.githubusercontent.com/32114380/160757946-906bca10-6267-4f5a-b6e5-d8e285970a1e.png)

**Comment by spencerwooo** [comment]
另外昨天还遇到：

<img width="654" alt="image" src="https://user-images.githubusercontent.com/32114380/160758014-68bb9966-5883-4aed-9354-9af2c70527fb.png">

不知道是不是跟你一样的问题？米游社的资料可能需要公开才行。

**Comment by spencerwooo** [comment]
另外也可以在手机上抓米游社的 API 包，看一下米游社这边发 API 时带的 Cookie 能不能用：

<img src="https://user-images.githubusercontent.com/32114380/160758423-8baf09f2-b156-41fb-ae94-4c90a0857871.jpeg" width="400" />

**Comment by dingyx99** [comment]
我现在直接抓的米游社的同URL请求，但是测试配置的时候还是会提示错误，我先检查一下我自己的隐私设置吧

**Comment by dingyx99** [comment]
![image](https://user-images.githubusercontent.com/11485117/160762062-1b5dbe07-90b0-43e0-8ea4-1dc210366d43.png)

**Comment by dingyx99** [comment]
似乎还是不太对？

**Comment by spencerwooo** [comment]
呃，你的 API 返回的东西都有吗？

https://github.com/spencerwooo/PaimonMenuBar/blob/e1700574b57106b7b93414437cb125ec71314324/PaimonMenuBar/GameRecord.swift#L10-L41

**Comment by dingyx99** [comment]
<img width="717" alt="截屏2022-03-30 14 25 55" src="https://user-images.githubusercontent.com/11485117/160765333-de12bb2a-e72f-4c8e-9c71-18136c9f653b.png">

**Comment by spencerwooo** [comment]
如果本地有 Xcode 可以编译项目的话：

https://github.com/spencerwooo/PaimonMenuBar/blob/e1700574b57106b7b93414437cb125ec71314324/PaimonMenuBar/Networking.swift#L63

在这里下面加上：

```swift
if let string = String(bytes: data, encoding: .utf8) {
    print(string)
}
```

然后看看项目有没有成功把数据请求下来？

因为毕竟你直接给我 Cookie 也是不方便，我也没办法帮你 debug……

**Comment by dingyx99** [comment]
我试试看，本地有条件的
