### ISSUE TITLE
Any plan to support macOS 11 ?

### ISSUE THREAD

**Issue by dreampiggy** [spencerwooo/PaimonMenuBar#11]
or even 10.15 ?

Swift concurrency support back-port to macOS 10.15/iOS 13.

And I can even install Xcode 13.3 on macOS 11, with some tweak :)

If you need help, maybe I can have a fork and PR in this weekend.

**Comment by spencerwooo** [comment]
> - [ ] Backward-compatibility for macOS 11.0

So, yes please! Thanks! Things preventing me adding support for older macOS versions are mostly just `async` fetch that are specific to macOS 12+ :(

**Comment by dreampiggy** [comment]
Hi.

I fork and modify some back-port API to make it work on macOS 11.0

However, I'm not quite expert at i18n. Is this showing correctly ?

Because I just **translate** the `String(:localized)` API to the old style one :)

I only test the `en-US` and `zh-Hans` locale.

<img width="584" alt="截屏2022-05-06 下午9 44" src="https://user-images.githubusercontent.com/6919743/167145819-e44f1067-17c8-44d9-a876-b1611f326432.png">

And, I use [Kingfisher](https://github.com/onevcat/Kingfisher) instead of `AsyncImage`, which have a better cache (The `AsyncImage` is never cached, means each time the icon should be loaded from HTTP)

**Comment by dreampiggy** [comment]
See #12 

Since my old MacBook Pro use macOS 11.4 and not ready to upgrad to macOS 12 (waiting for M1 Pro MacBook, in Shanghai...)

I can not test whether it's pixel match with the previous App running on macOS 12. But acutally I found it's OK for me to use now 😴

**Comment by spencerwooo** [comment]
Closing in favor of #12

**Comment by dreampiggy** [comment]
The badget in README.md seems not updated :)
![image](https://user-images.githubusercontent.com/6919743/167354047-0e9abdc2-0b72-4ff1-aeb4-f8597884a80b.png)

**Comment by spencerwooo** [comment]
> The badges in README.md seems not updated :)

Yes, I'm aware - waiting for a future time to sneak this tiny update in a larger commit :)
