### ISSUE TITLE
Cookie issue

### ISSUE THREAD

**Issue by voltaicspy** [spencerwooo/PaimonMenuBar#14]
i have been trying forever to fix this, but whenever i input my cookie, it always just shows
![image](https://user-images.githubusercontent.com/95888304/173309320-0a028a93-fba3-4b01-bded-72be48e26237.png)
my server is asia, and the browser i used to get my cookie is Brave.
regards.

**Comment by spencerwooo** [comment]
> **It is not working! Why?**
>
> Most often it is your cookie problem. You need to make sure that you have turned on Real-Time Notes under Battle Chronicle inside [HoYoLAB](https://www.hoyolab.com/article/1265396) or 实时便签 inside 米游社, depending on your server. You would also have to set your profile to public (instructions for [HoYoLAB](https://www.hoyolab.com/article/117720) (a bit futher down the page) / [米游社](https://www.9game.cn/yuanshen/5606032.html)).

Check [FAQ](https://paimon.swo.moe/), there are some things to configure on your end before you can use your cookie.
