### ISSUE TITLE
Can't get cookie from miyoushe

### ISSUE THREAD

**Issue by kiaia** [spencerwooo/PaimonMenuBar#23]
Mihoyo seems to have updated the website and it seems the cookie is different from the previous version. 
Is there some other way to get the cookie and make the PaimonMenuBar work？
Thx a lot.

**Comment by spencerwooo** [comment]
Try https://user.mihoyo.com/, this seems to be unchanged.

**Comment by spencerwooo** [comment]
If it still doesn't work, you may have to capture the packet for the API request via MITM on iOS.

**Comment by spencerwooo** [comment]
Closing this as the website <https://bbs.mihoyo.com/ys/> is back.
