### ISSUE TITLE
The colored icon seems to be discordant

### ISSUE THREAD

**Issue by breezewish** [spencerwooo/PaimonMenuBar#3]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/1916485/165948148-03d2fe29-4ccd-4aa1-be03-97530c8e3e4b.png">

<img width="568" alt="image" src="https://user-images.githubusercontent.com/1916485/165948182-883962a4-5691-4db6-ba2c-269fde567cf5.png">

The colored icon seems to be not well-fitted with other MacOS apps :)

Do you consider using a pure-colored icon (which renders as a white icon or a black icon), just like other Apps?

**Comment by spencerwooo** [comment]
I would prefer that as a configurable settings - will consider. 👍
