### ISSUE TITLE
Fetch is always failed if server is untouched

### ISSUE THREAD

**Issue by breezewish** [spencerwooo/PaimonMenuBar#7]
Reproduce workflow:

1. Clear all saved user defaults by using `defaults delete spencerwoo.PaimonMenuBar`
2. Start App
3. Enter UID
4. Enter Cookie
5. Click "Test config"

A "Failed to fetch" will be shown. If I do this further, then the config test will be succeeded:

1. Click "天空岛" (which is the default selected)
2. Click "Test config" again

**Comment by spencerwooo** [comment]
Should be fixed by b61b83d5363f4776f801805fadaf56688ad0cbdc (hopefully)
